name: blog_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.3.0
  firebase_auth: ^5.2.0
  google_fonts: ^6.2.1
  rxdart: ^0.27.2
  provider: ^6.1.2
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "lib/assets/icon/android_icon.png"
